import { useEffect, useRef, useState } from 'react';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const langs = [['en-IN','English'],['hi-IN','हिंदी'],['kn-IN','ಕನ್ನಡ'],['ta-IN','தமிழ்'],['te-IN','తెలుగు'],['ml-IN','മലയാളം']];

export default function LandingAuth({ done }) {
  const [mode, setMode] = useState('login'); const [lang, setLang] = useState(localStorage.getItem('arogya_lang_code') || 'en-IN'); const [copy, setCopy] = useState({}); const [conditions, setConditions] = useState([]); const [form, setForm] = useState({ username:'', email:'', password:'', age:25 }); const [error, setError] = useState(''); const google = useRef(null);
  const finish = async tokens => { localStorage.setItem('arogya_access_token', tokens.access_token); localStorage.setItem('arogya_refresh_token', tokens.refresh_token); done(await fetch(`${API}/auth/me`, { headers:{ Authorization:`Bearer ${tokens.access_token}` } }).then(r => r.json())); };
  useEffect(() => { fetch(`${API}/content/static?lang=${lang}`).then(r => r.json()).then(x => setCopy(x.content || {})); localStorage.setItem('arogya_lang_code', lang); }, [lang]);
  useEffect(() => { const id=import.meta.env.VITE_GOOGLE_CLIENT_ID; const timer=setInterval(() => { if (!id || !window.google?.accounts?.id || !google.current) return; clearInterval(timer); window.google.accounts.id.initialize({ client_id:id, callback:async ({credential}) => { try { const r=await fetch(`${API}/auth/google`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({credential}) }); if (!r.ok) throw Error((await r.json()).detail); finish(await r.json()); } catch(e) { setError(e.message); } } }); window.google.accounts.id.renderButton(google.current, { theme:'outline', size:'large', text:'continue_with', width:330 }); }, 120); return () => clearInterval(timer); }, []);
  const t=(key, fallback) => copy[key] || fallback;
  const submit = async e => { e.preventDefault(); setError(''); try { if (mode === 'register') { const r=await fetch(`${API}/auth/register`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ ...form, age:+form.age, language_id:langs.findIndex(x=>x[0]===lang)+1, has_health_condition:conditions.length>0, condition_ids:conditions }) }); if (!r.ok) throw Error((await r.json()).detail); } const r=await fetch(`${API}/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email:form.email,password:form.password}) }); if (!r.ok) throw Error((await r.json()).detail); finish(await r.json()); } catch(e) { setError(e.message); } };
  return <main className="welcome"><section className="art"><img src="/arogya-route-logo.png" alt="ArogyaRoute"/></section><section className="auth"><div className="auth-top"><div className="logo"><img src="/arogya-route-logo.png" alt="ArogyaRoute"/><b>{t('app.name','ArogyaRoute')}</b></div><select value={lang} onChange={e=>setLang(e.target.value)}>{langs.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><span className="eyebrow">{t('hero.eyebrow','PERSONAL AIR-CARE')}</span><h1>{t('hero.title','Plan journeys that are better to breathe.')}</h1><p>{t('hero.description','Compare pollution exposure and get practical health guidance.')}</p><form onSubmit={submit}><div className="tabs"><button type="button" className={mode==='login'?'selected':''} onClick={()=>setMode('login')}>{t('auth.submit','Sign in')}</button><button type="button" className={mode==='register'?'selected':''} onClick={()=>setMode('register')}>{t('auth.create_account','Create account')}</button></div>{mode==='register'&&<label>{t('profile.name','Name')}<input required onChange={e=>setForm({...form,username:e.target.value})}/></label>}<label>{t('auth.email','Email')}<input required type="email" onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{t('auth.password','Password')}<input required type="password" onChange={e=>setForm({...form,password:e.target.value})}/></label>{mode==='register'&&<><label>Age<input type="number" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/></label><label>{t('health.conditions','Health conditions')}<select multiple value={conditions} onChange={e=>setConditions([...e.target.selectedOptions].map(x=>+x.value))}><option value="1">Asthma</option><option value="2">COPD</option><option value="3">Heart Disease</option><option value="4">Pregnancy</option><option value="5">Senior Citizen</option><option value="6">Other Respiratory Issues</option></select></label></>}{error&&<p className="notice">{error}</p>}<button className="primary wide">{mode==='login'?t('auth.submit','Sign in'):t('auth.create_account','Create account')}</button></form><div className="google-login"><span>or continue with</span><div ref={google}/></div></section></main>;
}
